name: Django CI

on: ["push"]

jobs:    
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        envkey_DEVELOPMENT_KEY: ${{ secrets.DEVELOPMENT_KEY }}
        envkey_SANDBOX_KEY: ${{ secrets.SANDBOX_KEY }}
        directory: ../..
        file_name: .env
        fail_on_empty: false
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
